---
- name: Begin system configuration
  become: yes
  block:

  - name: Update 127.0.1.1 hosts entry (w/ FQDN)
    lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: "127.0.1.1\t{{ ansible_fqdn }} {{ ansible_hostname }}"
    when: ansible_fqdn != ansible_hostname

  - name: Update 127.0.1.1 hosts entry (w/o FQDN)
    lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: "127.0.1.1\t{{ ansible_fqdn }}"
    when: ansible_fqdn == ansible_hostname

  - when: ansible_distribution in ["Debian", "OSMC"]
    block:

    - name: Set Debian backports repository name
      set_fact:
        backports_apt_repository_name: "{{ ansible_distribution_release }}-backports"

    - name: Add Debian backports repository
      apt_repository:
        repo: "deb http://deb.debian.org/debian {{ backports_apt_repository_name }} main"
        filename: "{{ backports_apt_repository_name }}"

  - name: Add basic CLI tools
    apt:
      name: "{{ common_system_base_packages + common_system_extra_packages }}"

  - name: Update the command-not-found cache
    command: /usr/sbin/update-command-not-found
    # Command is not present on Ubuntu distribution
    when: ansible_distribution in ["Debian", "OSMC"]
