---
- name: Add lvm2 package
  apt:
    name: lvm2
  become: yes

- name: Gather ansible_lvm facts
  setup:
    # LVM facts have to be collected as root, but collecting all
    # facts as root will reset user details like ansible_user_id
    # to root.  Collect the minimum subset to pick up LVM facts.
    gather_subset: "!all,!min,hardware"
  become: yes

- name: Ensure we have ansible_lvm facts
  assert:
    that: ansible_lvm is defined
