---
- name: Begin OpenVPN configuration
  become: yes
  block:

  - name: Add required packages for OpenVPN
    apt:
      name:
      - openvpn
      - unzip

  - name: Create directory for openvpn files
    file:
      path: /etc/openvpn/pia
      state: directory
    register: pia

  - name: Download openvpn files for privateinternetaccess
    unarchive:
      remote_src: yes
      src: https://www.privateinternetaccess.com/openvpn/openvpn.zip
      dest: "{{ pia.path }}"
      creates: "{{ pia.path }}/ca.rsa.2048.crt"

  - name: List openvpn files for privateinternetaccess
    find:
      paths: "{{ pia.path }}"
      patterns: "*.ovpn"
    register: pia_config

  - name: Tweak openvpn files to use a credentials file
    lineinfile:
      path: "{{ item }}"
      line: auth-user-pass pia.credentials
      regexp: ^auth-user-pass
    loop: "{{ pia_config.files | map(attribute='path') | list }}"
    notify: Restart openvpn

  - name: Add privateinternetaccess credentials
    copy:
      content: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65386633353866633366616662373861323433613133393535653132633261343562373336353431
        6537366332643536623536323634336432393731396433660a323030396466396433613661366465
        32643231373963616335623439643131653966323536336534663438373464336266326662343738
        6361343139306134610a663139653132386363336663356436656631353266346361343037383665
        30613334343663356166333863626462373133623733306464306433613662376535
      dest: /etc/openvpn/pia.credentials
      mode: u=rw,g=,o=
      owner: root
      group: root
    no_log: True
    notify: Restart openvpn

  - name: Link openvpn configuration to the preferred server
    file:
      src: "{{ pia.path }}/{{ privateinternetaccess_server }}.ovpn"
      dest: /etc/openvpn/default.conf
      state: link
    notify: Restart openvpn

  - name: Enable openvpn
    systemd_service:
      name: openvpn.service
      enabled: true
      state: started

- name: Add bash aliases
  copy:
    src: bash_aliases
    dest: "{{ bash_aliases_dir }}/{{ role_name }}_aliases"
