---
- name: Begin journal configuration
  become: yes
  block:

  - name: Limit journal disk usage
    lineinfile:
      path: /etc/systemd/journald.conf
      regexp: "^#?SystemMaxUse="
      line: "SystemMaxUse={{ journal_max_disk_usage }}"
    notify: Restart journald
