---
- name: Set hostname to match inventory
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  become: yes

- name: Update 127.0.1.1 hosts entry
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1\t{{ inventory_hostname }}"
  become: yes

- name: Set backports repository name
  set_fact:
    backports_apt_repository_name: "{{ ansible_lsb.codename }}-backports"

- name: Add backports repository
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ backports_apt_repository_name }} main"
    filename: "{{ backports_apt_repository_name }}"
  become: yes

- name: Add desirable packages
  apt:
    name:
    - apt-file
    - bash-completion
    - bind9-dnsutils
    - command-not-found
    - git
    - htop
    - lsof
    - man-db
    - powerline
    - python3-powerline
    - rsync
    - tmux
    - usbutils
    - vim-addon-manager
    - vim-nox
  become: true

- name: Update the command-not-found cache
  command: /usr/sbin/update-command-not-found
  become: true

- name: Copy dotfiles to home directory
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item | basename }}"
  with_fileglob: "dotfiles/*"

- name: Copy XDG_CONFIG_HOME directory
  copy:
    src: config/
    dest: "{{ ansible_user_dir }}/.config/"
    mode: u=rw,g=r,o=r

- name: Add powerline to vim
  command: vim-addons install powerline

- name: Clone vim-colors-solarized as a Vim package
  git:
    repo: https://github.com/altercation/vim-colors-solarized.git
    dest: "{{ ansible_user_dir }}/.vim/pack/plugins/opt/vim-colors-solarized"
