---
- name: Set hostname to match inventory
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  become: yes

- name: Update 127.0.1.1 hosts entry
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1\t{{ inventory_hostname }}"
  become: yes

- name: Set backports repository name
  set_fact:
    backports_apt_repository_name: "{{ ansible_lsb.codename }}-backports"

- name: Add backports repository
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ backports_apt_repository_name }} main"
    filename: "{{ backports_apt_repository_name }}"
  become: yes

- name: Add desirable packages
  apt:
    name:
    - apt-file
    - bash-completion
    - bind9-dnsutils
    - command-not-found
    - htop
    - lsof
    - man-db
    - rsync
    - tmux
    - usbutils
  become: true

- name: Update the command-not-found cache
  command: /usr/sbin/update-command-not-found
  become: true

- name: Create config directories
  file:
    path: "{{ ansible_user_dir }}/.config/{{ item }}"
    state: directory
  loop:
  - bash_profile
  - tmux

- name: Source additional bash configurations
  blockinfile:
    path: "{{ ansible_user_dir }}/.profile"
    block: |
      if [ -n "$BASH_VERSION" ]; then
          if [ -d ~/.config/bash_profile ]; then
              for file in $(ls ~/.config/bash_profile); do
                  if [ -r ~/.config/bash_profile/$file ]; then
                      . ~/.config/bash_profile/$file
                  fi
              done
          fi
      fi

- name: Copy dotfiles to home directory
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item | basename }}"
  with_fileglob: "dotfiles/*"
