---
- name: Add git and related packages
  apt:
    name:
    - git
    - tig
  become: true

- name: Add git configuration
  template:
    src: gitconfig.j2
    dest: "{{ ansible_user_dir }}/.gitconfig"
