#!/usr/bin/bash

if nmcli --fields type --terse connection show --active | grep --quiet vpn
then
    # Use LOGNAME instead of USER so this works as a cron job.
    pass show redhat.com | head --lines 1 | kinit ${LOGNAME}@IPA.REDHAT.COM > /dev/null && klist
else
    echo "Cannot renew Red Hat Kerberos token: no active VPN connection" > /dev/stderr
fi
