:scriptencoding utf-8

" Load plugin and indent files for specific file types
filetype plugin indent on

" Use the solarized colorscheme
syntax enable
set background=dark
colorscheme solarized

" Set backspace behavior
set backspace=indent,eol,start

" Use UTF-8 encoding
set encoding=utf-8

" Do not expand tab characters into spaces
set noexpandtab

" Highlight search pattern matches
set hlsearch

" Show tabs, trailing whitespace, and continued lines visually
set list listchars=tab:»·,trail:·,extends:…

" Show line numbers
set number

"------------------------------------------
" Supplemental configuration for powerline
"------------------------------------------

" Always display the statusline in all windows
set laststatus=2

" Always display the tabline, even if there is only one tab
set showtabline=2

" Hide the default mode text (e.g. -- INSERT -- below the statusline)
set noshowmode
